# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: "My Workflow"
description: "A collection of tricks to work faster."

exclude:
  - Gemfile
  - Gemfile.lock
  - '*.yml'
  - sass
  - config.rb
  - scss
  - env.sh
  - '*.sh'
  - '*.scss'
  - '*.BAK'

pygments: true
markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md


host:        127.0.0.1
port:        4000
baseurl:     /
url:         http://MattReimer.github.io/my-workflow
lsi:         false
